<?php

namespace ContainerN4W5DVf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_26_MyXFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.26.MyXF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.26.MyXF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'evalSlotService' => ['privates', 'App\\Service\\EvalSlotService', 'getEvalSlotServiceService', true],
            'experienceService' => ['privates', 'App\\Service\\ExperienceService', 'getExperienceServiceService', true],
            'searchBarService' => ['privates', 'App\\Service\\SearchBarService', 'getSearchBarServiceService', true],
        ], [
            'em' => '?',
            'evalSlotService' => 'App\\Service\\EvalSlotService',
            'experienceService' => 'App\\Service\\ExperienceService',
            'searchBarService' => 'App\\Service\\SearchBarService',
        ]);
    }
}
