<?php

namespace ContainerN4W5DVf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PXihOY6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PXihOY6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PXihOY6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'evalSlotRepository' => ['privates', 'App\\Repository\\EvalSlotRepository', 'getEvalSlotRepositoryService', true],
            'evaluationRequestRepository' => ['privates', 'App\\Repository\\ProjectEvaluationRequestRepository', 'getProjectEvaluationRequestRepositoryService', true],
            'project' => ['privates', '.errored..service_locator.PXihOY6.App\\Entity\\Project', NULL, 'Cannot autowire service ".service_locator.PXihOY6": it needs an instance of "App\\Entity\\Project" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'evalSlotRepository' => 'App\\Repository\\EvalSlotRepository',
            'evaluationRequestRepository' => 'App\\Repository\\ProjectEvaluationRequestRepository',
            'project' => 'App\\Entity\\Project',
        ]);
    }
}
