<?php

namespace ContainerN4W5DVf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OKrjGtBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OKrjGtB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OKrjGtB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'searchBarService' => ['privates', 'App\\Service\\SearchBarService', 'getSearchBarServiceService', true],
        ], [
            'searchBarService' => 'App\\Service\\SearchBarService',
        ]);
    }
}
