<?php

namespace ContainerN4W5DVf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Bq7rhnrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Bq7rhnr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Bq7rhnr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'newEnd' => ['privates', '.errored..service_locator.Bq7rhnr.DateTime', NULL, 'Cannot autowire service ".service_locator.Bq7rhnr": it references class "DateTime" but no such service exists.'],
            'newStart' => ['privates', '.errored..service_locator.Bq7rhnr.DateTime', NULL, 'Cannot autowire service ".service_locator.Bq7rhnr": it references class "DateTime" but no such service exists.'],
            'user' => ['privates', '.errored..service_locator.Bq7rhnr.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.Bq7rhnr": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'newEnd' => 'DateTime',
            'newStart' => 'DateTime',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
