<?php

namespace ContainerN4W5DVf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TwaqI8WService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.twaqI8W' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.twaqI8W'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'chatRepo' => ['privates', 'App\\Repository\\ChatMessageRepository', 'getChatMessageRepositoryService', true],
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'chatRepo' => 'App\\Repository\\ChatMessageRepository',
            'userRepo' => 'App\\Repository\\UserRepository',
        ]);
    }
}
