<?php

namespace ContainerN4W5DVf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEvalSlotServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\EvalSlotService' shared autowired service.
     *
     * @return \App\Service\EvalSlotService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/EvalSlotService.php';

        return $container->privates['App\\Service\\EvalSlotService'] = new \App\Service\EvalSlotService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));
    }
}
