<?php

namespace ContainerN4W5DVf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEvalSlotTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\EvalSlotType' shared autowired service.
     *
     * @return \App\Form\EvalSlotType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/EvalSlotType.php';

        return $container->privates['App\\Form\\EvalSlotType'] = new \App\Form\EvalSlotType();
    }
}
