<?php

namespace ContainerTLVpg8p;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0l5GIK_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0l5GIK.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0l5GIK.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'projectRepo' => ['privates', 'App\\Repository\\ProjectRepository', 'getProjectRepositoryService', true],
            'userProjectRepository' => ['privates', 'App\\Repository\\UserProjectRepository', 'getUserProjectRepositoryService', true],
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'em' => '?',
            'projectRepo' => 'App\\Repository\\ProjectRepository',
            'userProjectRepository' => 'App\\Repository\\UserProjectRepository',
            'userRepo' => 'App\\Repository\\UserRepository',
        ]);
    }
}
