<?php

namespace ContainerTLVpg8p;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FrZW9ikService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FrZW9ik' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FrZW9ik'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'chatRepo' => ['privates', 'App\\Repository\\ChatMessageRepository', 'getChatMessageRepositoryService', true],
            'projectRepo' => ['privates', 'App\\Repository\\ProjectRepository', 'getProjectRepositoryService', true],
            'userProjectRepository' => ['privates', 'App\\Repository\\UserProjectRepository', 'getUserProjectRepositoryService', true],
        ], [
            'chatRepo' => 'App\\Repository\\ChatMessageRepository',
            'projectRepo' => 'App\\Repository\\ProjectRepository',
            'userProjectRepository' => 'App\\Repository\\UserProjectRepository',
        ]);
    }
}
