<?php

namespace ContainerTLVpg8p;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCleanExpiredSlotsCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\CleanExpiredSlotsCommand' shared autowired service.
     *
     * @return \App\Command\CleanExpiredSlotsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/CleanExpiredSlotsCommand.php';

        $container->privates['App\\Command\\CleanExpiredSlotsCommand'] = $instance = new \App\Command\CleanExpiredSlotsCommand(($container->privates['App\\Repository\\EvalSlotRepository'] ?? $container->load('getEvalSlotRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));

        $instance->setName('app:clean-expired-slots');
        $instance->setDescription('Clean up expired evaluation slots');

        return $instance;
    }
}
