<?php

namespace ContainerTLVpg8p;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCleanExpiredSlotsCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\CleanExpiredSlotsCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\CleanExpiredSlotsCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:clean-expired-slots', [], 'Clean up expired evaluation slots', false, #[\Closure(name: 'App\\Command\\CleanExpiredSlotsCommand')] fn (): \App\Command\CleanExpiredSlotsCommand => ($container->privates['App\\Command\\CleanExpiredSlotsCommand'] ?? $container->load('getCleanExpiredSlotsCommandService')));
    }
}
