<?php

namespace ContainerTLVpg8p;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRemoveEventTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\RemoveEventType' shared autowired service.
     *
     * @return \App\Form\RemoveEventType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/RemoveEventType.php';

        return $container->privates['App\\Form\\RemoveEventType'] = new \App\Form\RemoveEventType();
    }
}
