<?php

namespace ContainerTLVpg8p;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSearchBarServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\SearchBarService' shared autowired service.
     *
     * @return \App\Service\SearchBarService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/SearchBarService.php';

        return $container->privates['App\\Service\\SearchBarService'] = new \App\Service\SearchBarService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));
    }
}
