<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTLVpg8p\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTLVpg8p/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTLVpg8p.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTLVpg8p\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTLVpg8p\App_KernelDevDebugContainer([
    'container.build_hash' => 'TLVpg8p',
    'container.build_id' => '0b51c4dd',
    'container.build_time' => 1754410856,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTLVpg8p');
