<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'confirmationToken' => [parent::class, 'confirmationToken', null, 16],
        "\0".parent::class."\0".'created' => [parent::class, 'created', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'evalPoints' => [parent::class, 'evalPoints', null, 16],
        "\0".parent::class."\0".'evalSlots' => [parent::class, 'evalSlots', null, 16],
        "\0".parent::class."\0".'events' => [parent::class, 'events', null, 16],
        "\0".parent::class."\0".'experience' => [parent::class, 'experience', null, 16],
        "\0".parent::class."\0".'first_name' => [parent::class, 'first_name', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'image' => [parent::class, 'image', null, 16],
        "\0".parent::class."\0".'isActive' => [parent::class, 'isActive', null, 16],
        "\0".parent::class."\0".'last_name' => [parent::class, 'last_name', null, 16],
        "\0".parent::class."\0".'level' => [parent::class, 'level', null, 16],
        "\0".parent::class."\0".'notifications' => [parent::class, 'notifications', null, 16],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null, 16],
        "\0".parent::class."\0".'role' => [parent::class, 'role', null, 16],
        "\0".parent::class."\0".'unreadNotificationsCount' => [parent::class, 'unreadNotificationsCount', null, 16],
        "\0".parent::class."\0".'userProjects' => [parent::class, 'userProjects', null, 16],
        'confirmationToken' => [parent::class, 'confirmationToken', null, 16],
        'created' => [parent::class, 'created', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'evalPoints' => [parent::class, 'evalPoints', null, 16],
        'evalSlots' => [parent::class, 'evalSlots', null, 16],
        'events' => [parent::class, 'events', null, 16],
        'experience' => [parent::class, 'experience', null, 16],
        'first_name' => [parent::class, 'first_name', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'image' => [parent::class, 'image', null, 16],
        'isActive' => [parent::class, 'isActive', null, 16],
        'last_name' => [parent::class, 'last_name', null, 16],
        'level' => [parent::class, 'level', null, 16],
        'notifications' => [parent::class, 'notifications', null, 16],
        'password' => [parent::class, 'password', null, 16],
        'role' => [parent::class, 'role', null, 16],
        'unreadNotificationsCount' => [parent::class, 'unreadNotificationsCount', null, 16],
        'userProjects' => [parent::class, 'userProjects', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
